# Generated by Django 4.2.2 on 2024-01-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_classifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifier',
            old_name='response',
            new_name='prompt',
        ),
        migrations.RenameField(
            model_name='classifier',
            old_name='statement',
            new_name='sentiment',
        ),
    ]
