# Generated by Django 4.2.2 on 2024-02-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_response_classifier_prompt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.RemoveField(
            model_name='classifier',
            name='prompt',
        ),
        migrations.AddField(
            model_name='classifier',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='classifier',
            name='ticker',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='sentiment',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
