# Generated by Django 4.2.2 on 2024-02-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_delete_data_remove_classifier_prompt_classifier_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classifier',
            new_name='News',
        ),
    ]
