# Generated by Django 4.2.2 on 2024-02-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_rename_classifier_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
