# Generated by Django 4.2.2 on 2024-03-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_news_title_alter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=20)),
                ('ticker', models.CharField(default='', max_length=4)),
                ('aggregate', models.IntegerField(default=0)),
            ],
        ),
    ]
