# Generated by Django 4.2.2 on 2024-03-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_tickerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerrating',
            name='rating',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='news',
            name='ticker',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='tickerrating',
            name='aggregate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tickerrating',
            name='ticker',
            field=models.CharField(default='', max_length=5),
        ),
    ]
