# Generated by Django 4.2.2 on 2024-05-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=20)),
                ('Symbol', models.CharField(default='', max_length=5)),
                ('rating', models.CharField(default='', max_length=10)),
                ('aggregate', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='TickerRating',
        ),
    ]
