# Generated by Django 4.2.2 on 2024-05-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_symbolrating_delete_tickerrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbolrating',
            old_name='Symbol',
            new_name='symbol',
        ),
    ]
